base_lr: 0.1
batch_size: 12
config: config/st_gcn/nturgbd-cross-subject/train.yaml
device:
- 0
eval_interval: 5
feeder: st_gcn.feeder.Feeder
ignore_weights: []
log_interval: 100
model: st_gcn.net.ST_GCN
model_args:
  channel: 3
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: spatial
  mask_learning: true
  num_class: 60
  num_person: 2
  num_point: 25
  use_data_bn: true
  window_size: 300
nesterov: true
num_epoch: 80
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_interval: 10
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 10
- 50
test_batch_size: 64
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/val_data.npy
  label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
  mode: test
  window_size: 300
train_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/xsub/train_label.pkl
  mode: train
  window_size: 300
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/NTU-RGB-D/xsub/ST_GCN
